version: "3.8"
networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
#  mysql:
#    driver: ${VOLUMES_DRIVER}
  pgsql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:

  ### Application(PHP/Laravel  php-fpm) #########################################
  php-fpm:
    container_name: ${PROJECT_NAME}-php
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ${WORK_DIR_BACKEND}:/var/www/application
      - ./docker/php-fpm/settings/php.dev.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php-fpm/settings/www.dev.conf:/usr/local/etc/php-fpm.d/www.confFROM
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=${PROJECT_NAME}-psgl
      - DB_PORT=5432
      - DB_DATABASE=${PSGL_NAME}
      - DB_USERNAME=${PSGL_USER}
      - DB_PASSWORD=${PSGL_PASSWORD}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - pgsql
    networks:
      - backend

  ### NGINX Server #########################################
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${WORK_DIR_BACKEND}:/var/www/application
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ${DATA_PATH}/logs/nginx:/var/log/nginx
      - ./docker/nginx/certs:/etc/ssl/certs
    depends_on:
      - php-fpm
    networks:
      - backend

  ### Nodejs(Laravel) ################################################
  node:
    container_name: ${PROJECT_NAME}-node
    ports:
      - 5173:5173
    build:
      context:  ./docker/node
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${WORK_DIR_BACKEND}:/var/www/application:delegated
    #    depends_on:
    #      - redis
    networks:
      - backend

  ### PostgreSQL #################################################
  pgsql:
    container_name: ${PROJECT_NAME}-psgl
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    ports:
      - ${PSGL_PORT}:5432
    environment:
      POSTGRES_DB: ${PSGL_NAME}
      POSTGRES_USER: ${PSGL_USER}
      POSTGRES_PASSWORD: ${PSGL_PASSWORD}
      PGTZ: 'Asia/Tokyo'
    volumes:
      - ${DATA_PATH}/db/postgres-data:/var/lib/postgresql
      - ${DATA_PATH}/db/postgres/script:/docker-entrypoint-initdb.d
    networks:
      - backend

  ### Redis ################################################
  redis:
    container_name: ${PROJECT_NAME}-redis
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${DATA_PATH}/db/redis:/data
    networks:
      - backend